### ISSUE TITLE
range

### ISSUE THREAD

**Issue by DecentMakeover** [chippybautista/CVMIG-VertebraeClassification#1]
Hi 

Whats the range to normalize the vertebrae images? like in liver we usually normalize it between -100 to 400.Thanks

**Comment by chippybautista** [comment]
Hi, we did not have to do normalization because we used the segmentation masks.
However, if you are talking about the hounsfield units (HU) used in medical imaging, iirc, the raw scans were already normalized when we got them.

**Comment by DecentMakeover** [comment]
oh okay
